### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [tyeonn/conbrite#1]
- [x] Make all search features a separate MVP or bonus MVP

Let me know if you have any questions or want more details!

**Comment by timjwu** [comment]
Hey, I separated the search into location and category. I'm not sure if this is what you meant, but if I should create a whole separate mvp for search, please let me know. Thanks!

**Comment by AdamYLiang** [comment]
Oh sorry for not being entirely clear, I meant the latter!
Search (for both location and category) should be an entire MVP. Since you already have 7 I would put search down as a bonus MVP for when you finish the rest.

**Comment by timjwu** [comment]
Alright I tweaked the mvp list again. Please let me know if there are more options I can implement (specifically on event and category) for the core MVP. Thank you!

**Comment by AdamYLiang** [comment]
Looks great! Nice bonus features as well.
