### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by AdamYLiang** [tyeonn/conbrite#2]
**Users Table** 
- [x] Separate `name` into `first_name` and `last_name`
I would not hold too much user information (phone #, job title, company id, address, etc.) initially since the the user auth MVP does not need it. You can feel free to add on to the table as you need later but try to trim down some fields. 

**Events Table**
- [x] Should have a column for the event image
What is the `type` field? 

**Location Table**
- [x] `city, state, country` should be `not null`

**General**
- [x] Joins table for categories and events
- [x] Change `follow_events` table name to `bookmarks` to match MVP
`like` and `follow_events` seems like it could just be a `bookmarks` table.

Let me know if you have any questions or want to talk about any of these!

**Comment by timjwu** [comment]
Hey! so I did all the revisions and as for the events, I took off type. Initially, I put that there b/c on eventbrite they had type as in dinner, convention, autoshow, festival, etc. and category as in family, games, auto, food, etc. Since they are very similar I got rid of it, but let me know if you think its worth leaving it there. Also I was just curious if I should link event address with location. Do I just keep those separate? Thank you

**Comment by AdamYLiang** [comment]
Gotcha, it's up to you if you want to leave type in! I was just unsure what it was since I thought it was the same as category when I was browsing the site. 

As for the link between event address and location, I think it's enough to have the association since you can just look at the event and pull out the address that way.

Other than the changes look good, I just have a few more small tweaks:
**category_events Table** 
- [x] Remove individual unique index on `category_id` and `event_id`
- [x] Instead should have a unique index on `category_id` scoped in `event_id` so that one event cannot be added to the same category more than once.

**Comment by timjwu** [comment]
I created an index on the combination of category_id and event_id and made that combo unique. If this is not what you meant please let me know. Thanks!

**Comment by AdamYLiang** [comment]
Everything looks great here, nice work!
