### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [tyeonn/conbrite#3]
**Events**
- [x] Should have date created as well
- [x] Keeping track of ticket amount might be useful if you want to limit registrations later 

The rest of the state looks good! Let me know if you have any questions or want to talk about the state.

**Comment by timjwu** [comment]
Hey, so I added those two things, but can you please explain how I can utilize the date created for events? I'm not exactly sure why I need that right now. Thank you!

**Comment by AdamYLiang** [comment]
Good changes, let me know if you have any other questions!
