### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [tyeonn/conbrite#4]
Front end looks good, nice job! 
I have some small additions/changes for the backend routes:

**Bookmarks**
- [x] Should have a `:id` wildcard for `DELETE`
- [x] Should have API endpoints for `tickets`, perhaps nest it under the events
- [x] Should have API endpoints for `location`

Let me know if you have any questions or want to discuss the changes!

**Comment by timjwu** [comment]
I added an id wildcard for category_event also. Please let me know if I need that there!

**Comment by AdamYLiang** [comment]
Hey Tim, the route for the tickets are fine but I'd put it underneath it's own ticket category. 
Other than that it looks good!

**Comment by timjwu** [comment]
Hey adam, so does that mean to keep it under /events/tickets but just move that part down to its own tickets section? I made the change but let me know if this is what you meant. Thanks!

**Comment by AdamYLiang** [comment]
Exactly! Nice work.
