### ISSUE TITLE
Frontend Auth

### ISSUE THREAD

**Issue by timjwu** [tyeonn/conbrite#5]
## Frontend Auth

- [x] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user

_Use the space below for features specific to your app/MVP for review_
- [x] Finds email from backend correctly and displays relevant form
- [x] Can go back to main form to edit email
- [x] Logout clears store and returns to signin
- [x] Auth routes

### Additional Notes:
Still working on css

**Comment by AdamYLiang** [comment]
Looks good! Feel free to move onto the next MVP!
